### ISSUE TITLE
[Dev] likes show error 

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Likes#1]
#### Describe the bug

Whenever you get a vote for your island it gives you the error. 
/is likes
![image](https://user-images.githubusercontent.com/47111280/64919450-7bf0b080-d7b3-11e9-8411-2a069f9bf432.png)

And same to /is likes view <player>
![image](https://user-images.githubusercontent.com/47111280/64919454-8a3ecc80-d7b3-11e9-9c72-8da75d6b78bb.png)

 - OS: **Windows**
 - Java version: **8**

#### Plugins
![image](https://user-images.githubusercontent.com/47111280/64919464-b8241100-d7b3-11e9-8f69-cd728f3d7c5f.png)

![image](https://user-images.githubusercontent.com/47111280/64919470-c5410000-d7b3-11e9-9088-031cd90f6a99.png)

**Comment by BONNe** [comment]
I fixed the issue with `/is likes view <player>` command.
But I cannot reproduce the error with `/is likes` :(

**Comment by OverBrave** [comment]
Only when you type the command.

**Comment by OverBrave** [comment]
If it is your island has voted, and if you type this command gives an error.

**Comment by BONNe** [comment]
Could you try Build #4 and report if it is fixed?

**Comment by OverBrave** [comment]
I will try

**Comment by OverBrave** [comment]
Yes now working thx <3
