### ISSUE TITLE
Is likes TOP Command

### ISSUE THREAD

**Issue by NoHoPeLess** [BentoBoxWorld/Likes#11]
Hello when i try /is likes top it result in : an internal error occurred while attemting to perform this command console: https://hastebin.com/nidegujidu.cs

BentoBox v
https://s19.directupload.net/images/200219/2d24hit7.jpg

thanks for all :)

**Comment by NoHoPeLess** [comment]
I see its the same https://github.com/BentoBoxWorld/Likes/issues/10 close it?

**Comment by tastybento** [comment]
I got it in #10. I'm working on it now.
