### ISSUE TITLE
Ranking when resetting an island

### ISSUE THREAD

**Issue by SamuDu24** [BentoBoxWorld/Likes#12]
Hello !
I'm having a little problem with the addon...
First of all, I have version 1.7.1 of the addon (the last one).
I also specify that I use BentoBox version 1.12.0, and that I use PaperSpigot 1.15.2.

This is what happens when a player in the ranking resets his island. 
https://zupimages.net/up/20/17/s1i1.jpg

This happens in all cases, whether the reset-on-reset is on "true" or "false", when it should always be the same player, or it should not appear at all.

If a new like is added to the player's new island, here's what happens: 
https://zupimages.net/up/20/17/htcf.jpg
The two heads in the standings are supposed to be one player.

That's all, thank you !

**Comment by BONNe** [comment]
Hello,
Could you try snapshoot build from [Jenkins server](https://ci.codemc.org/job/BentoBoxWorld/job/Likes/)?

**Comment by SamuDu24** [comment]
With version 2.0.0-SNAPSHOT-b23, when a player resets his island and when the command **./is likes top** is performed, this happens: 
https://zupimages.net/up/20/17/vpms.jpg

**Comment by BONNe** [comment]
Could you check build version b24?

**Comment by SamuDu24** [comment]
Oof

`[BentoBox] AddonException : Addon 'plugins/BentoBox/addons/Likes-2.0.0-SNAPSHOT-b24-javadoc.jar' doesn't contains addon.yml file`

**Comment by BONNe** [comment]
That is a javadoc :)
Use  `Likes-2.0.0-SNAPSHOT-b24.jar`

**Comment by SamuDu24** [comment]
Oh my bad !
I knew that too, I just clicked too fast, sorry...

Same in the top after reset:
https://zupimages.net/up/20/17/ydf0.jpg

**Comment by BONNe** [comment]
Ok, I remembered :D

Likes is stored by Island.
OnReset by default it does not remove data from it. You can enable it in config. However, I will work on fixing so it is removed by default if the island is resetted :)

**Comment by SamuDu24** [comment]
All right ! :D
