### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Likes#14]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/87120497-38f35280-c289-11ea-97e3-044bfb1dbd9c.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/87120513-414b8d80-c289-11ea-9ec1-351b17244ce5.png)

**Comment by OverBrave** [comment]
This error only happens change mode to stars.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/87121139-caaf8f80-c28a-11ea-96dd-5cac0c16649f.png)

**Comment by BONNe** [comment]
Yes, sorry...
I forgot to change one method. Will fix it soon...
I do not know how I missed that.

**Comment by OverBrave** [comment]
Can you fix it right now?

**Comment by BONNe** [comment]
Latest development version should have fixed the issue.
