### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by Redemption2033** [BentoBoxWorld/Likes#2]
Am I blind or is there no download for this addon anywhere?

**Comment by BONNe** [comment]
You are not blind.
This addon is in the development phase.
It is almost ready, but not tested well.
Only available versions are in Jenkins server:
[![Build Status](https://ci.codemc.org/buildStatus/icon?job=BentoBoxWorld/Likes)](https://ci.codemc.org/job/BentoBoxWorld/job/Likes/)
