### ISSUE TITLE
WARN: Warps not found

### ISSUE THREAD

**Issue by Whitescan** [BentoBoxWorld/Likes#33]
### Expected behavior

There should be no warn since when refering to the [installation part of the documentation](https://docs.bentobox.world/en/latest/addons/Likes/#installation) it is not required to run this addon.

### Observed/Actual behavior

It warns about not finding the Warps Addon

### Steps/models to reproduce

Install BentoBox without the Warps Addon and add the Likes Addon.

### BentoBox version

1.19.0

### Plugin list

[Plugin-List](https://prnt.sc/26m250k) even if not really interesting for this issue.

**Comment by BONNe** [comment]
In general, it does not affect anything. 
But could you share output of command:

`/bentobox version`

**Comment by Whitescan** [comment]
> In general, it does not affect anything. But could you share output of command:
> 
> `/bentobox version`

[Sure](https://prnt.sc/26m35eh) it's in german but I think you kinda know what the important info is 😄

**Comment by BONNe** [comment]
This is not an issue.
The warps addon is used to allow teleporting via top menu, but due to the fact that warps is not installed it throwed warning.
In next version warning will not be there.
