### ISSUE TITLE
Error: Null when using likes top command

### ISSUE THREAD

**Issue by Whitescan** [BentoBoxWorld/Likes#34]
### Expected behavior

When running for example /ob likes top it should display the top list.

### Observed/Actual behavior

Shows Message "An internal error occurred while attempting to perform this command"

### Steps/models to reproduce

1. Setup a fresh server with BentoBox and Likes addon.
2. Use (in my case) /oba setspawn.
3. Use /like on serverspawn island
4. See message & [this stacktrace](https://pastebin.com/k0tZ7jci) in console

### BentoBox version

1.19.0

### Plugin list

[Plugin-List](https://prnt.sc/26m250k) even if not needed here.

**Comment by BONNe** [comment]
Relates to the #35
