### ISSUE TITLE
Likes can not be viewed on spawn island

### ISSUE THREAD

**Issue by Whitescan** [BentoBoxWorld/Likes#35]
### Expected behavior

When running for example /ob likes view it should display the current likes or what ever is configured.

### Observed/Actual behavior

You must be on the island to run this command!

### Steps/models to reproduce

1. Setup a fresh server with BentoBox and Likes addon.
2. Use (in my case) /oba setspawn.
3. Use /like on serverspawn island
4. See wrong behavior in chat...

### BentoBox version

1.19.0

### Plugin list

[Plugin-List](https://prnt.sc/26m250k) even if not needed here.

**Comment by BONNe** [comment]
I have a question, why do you need to like spawn island?

I was planning to block liking (staring) any non-owned island, which would include spawn island.

Is there a particular reason why spawn island should receive likes?

**Comment by Whitescan** [comment]
Because on most servers the local build team has build the spawn and they can see how people like it and if it needs to be rebuild.
But that would be neat. The actual issue is that the feedback of the command says it is not an island. But for the user it pretty much looks like one.
Should be something like: "You can't like / dislike server property" or something like that.
