### ISSUE TITLE
New Translate

### ISSUE THREAD

**Issue by WTFTWTM** [BentoBoxWorld/Likes#5]
### Additional context

[zh-CN [14].zip](https://github.com/BentoBoxWorld/Likes/files/3826107/zh-CN.14.zip)

Chinese!!!!!!

**Comment by WTFTWTM** [comment]
Sorry, Format error

Here is a new one

`likes:
  gui:
    titles:
      select-block: '&d选择一个方块'
      top: '&d[type] 排行榜'
      view: '&d查看好评岛屿'
      manage: '&d对当前岛屿进行评价'
      settings: '&d更改设置'
      admin: '&d管理员面板'
      select-island: '&d选择一个岛屿'
      select-player: '&d选择一个玩家'
      edit-view: '&d修改岛屿评价'
    buttons:
      cancel: '&c取消'
      accept: '&a确认'
      previous: 上一页
      next: '下一页'
      return: '&a返回'
      view-mode: '&6排行榜类型'
      name: '[name]'
      like: '&6好评计数'
      like-rank: '&6按好评排列'
      dislike: '&c差评计数'
      dislike-rank: '&c按差评排列'
      overall: '&a排名'
      overall-rank: '&a按排名排列'
      add-like: '&6添加/移除 好评'
      add-dislike: '&c添加/移除 差评'
      like-cost: '好评费用'
      like-remove-cost: '移除好评费用'
      dislike-cost: '差评费用'
      dislike-remove-cost: '移除差评费用'
      default-icon: '默认图标'
      inform-players: '通知岛屿成员'
      log-history: '历史日志'
      reset-likes: '重置岛屿时归零评价'
      manage-likes: '管理岛屿评价'
      likes-icon: '更改岛屿图标'
      wipe-data: '清空数据'
      edit-settings: '修改设置'
      add-dislike-user: '添加差评'
      add-like-user: '添加好评'
      remove-dislike-user: '移除差评'
      remove-like-user: '移除好评'
    descriptions:
      selected: '&d已选择'
      view-mode: '&f允许选择|&f应该显示|&f哪种排行'
      mode: '展示前十位|[type] 岛屿'
      top-value:
        likes: '&6[rank] 岛屿|&6拥有 [value] 个好评'
        dislikes: '&6[rank] 岛屿|&6拥有 [value] 个差评'
        rank: '&6[rank] 排名|&6拥有 [value] 排名分数'
      values: '岛屿拥有:|[likes] 个好评|[dislikes] 个差评|[rank] 排名分数'
      unknown: '&c未知玩家'
      current-value: '当前值: [value]'
      like: '好评被其他玩家 |所添加'
      dislike: '差评被其他玩家 |所添加'
      overall: '当前排名分|(likes - dislikes)'
      like-rank: '按照好评数|排名'
      dislike-rank: '按照差评数|排名'
      overall-rank: '按照排名分|排名'
      like-next: '展示下一个喜欢了|你的岛屿的玩家'
      dislike-next: '展示下一个差评了|你的岛屿的玩家'
      like-previous: '展示上一个喜欢了|你的岛屿的玩家'
      dislike-previous: '展示上一个差评了|你的岛屿的玩家'
      add-like: '允许添加|或移除好评'
      add-dislike: '允许添加|或移除差评'
      cost: '当前操作花费 $[value].'
      like-cost: '允许更改添加|好评的花费'
      like-remove-cost: '允许更改移除|好评的花费'
      dislike-cost: '允许更改添加|差评的花费'
      dislike-remove-cost: '允许更改移除|差评的花费'
      default-icon: '允许更改排行榜|默认图标'
      inform-players: '允许更改岛屿成员|是否收到来自|好评或者差评|的提醒'
      log-history: '允许更改是否|应该存储历史数据'
      reset-likes: '允许更改是否|在岛屿重置时|重置评价计数'
      manage-likes: '允许添加/删除|好评或差评了选中岛屿|的玩家'
      likes-icon: '允许更改在排行榜中的岛屿的图标'
      wipe-data: '允许完全删除|已经存储的游戏模式信息'
      edit-settings: '允许在GUI中编辑|插件信息'
  types:
    likes: '好评'
    dislikes: '差评'
    rank: '排名'
  messages:
    add-like: '&a你好评了 [island] 的岛屿'
    player-add-like: '&a玩家 [user] 好评了你的岛屿'
    remove-like: '&c你从 [island] 的岛屿上移除了你的好评'
    player-remove-like: '&c玩家 [user] 从你的岛屿上移除了他的好评'
    add-dislike: '&c你差评了 [island] 的岛屿'
    player-add-dislike: '&c[user] 差评了你的岛屿'
    remove-dislike: '&a你从 [island] 的岛屿移除了你的差评'
    player-remove-dislike: '&a玩家 [user] 从你的岛屿上移除了他的差评'
    no-data-about-island: '&e这个岛屿暂时无人评价'
    no-data-about-your-island: '&e你的岛屿暂时无人评价'
  errors:
    not-on-island: '&c你必须站在一个岛屿上才能使用这个命令'
    your-island: '&c你无法好评或差评你自己的岛屿'
    numeric-only: '&c输入只能接受数字!'
    not-valid-value: '&c数字需要大于 [min] 并且小于 [max],你提供的值 [value] 无法满足这个条件!'
    top-is-empty: '&c抱歉,排行榜上暂无任何人'
    database-error: '&c抱歉,数据库好像出了问题,无法找到你的岛屿信息'
  questions:
    prefix: '&e狐游 &6┃┃ &f '
    like-cost: '&5请输入好评所需要的费用'
    like-remove-cost: '&5请输入移除好评所需要的费用'
    dislike-cost: '&5请输入差评所需要的费用'
    dislike-remove-cost: '&5请输入移除差评所需要的费用'
  commands:
    admin:
      help:
        parameters: ''
        description: 打开管理员面板
      settings:
        parameters: ''
        description: 打开管理员设定面板
    help:
      parameters: ''
      description: 打开喜欢列表
    top:
      parameters: <type>
      description: 打开排行榜
    view:
      parameters: <player>
      description: 打开喜欢你的列表
`

**Comment by tastybento** [comment]
Thank you! Added in 65228ff23afaf0cb37fdfe08d8eab2c875cbaae5.

You can also join the translation team via [GitLocalize](https://gitlocalize.com). Just use your GitHub login and then you can use their interface to edit language files easily.
